language: go
sudo: false

go:
  - 1.6.2

install:
  - go get -v -t -d google.golang.org/appengine/...
  - go get -v -t -d github.com/Bogdanp/anom/...
  - mkdir sdk
  - curl -o sdk.zip "https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.24.zip"
  - unzip sdk.zip -d sdk
  - export APPENGINE_DEV_APPSERVER=$(pwd)/sdk/go_appengine/dev_appserver.py

script:
  - sdk/go_appengine/goapp test
