language: go
sudo: false

go:
  - 1.6.2

install:
  - mkdir sdk
  - curl -o sdk.zip "https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.24.zip"
  - unzip sdk.zip -d sdk
  - export APPENGINE_DEV_APPSERVER=$(pwd)/sdk/go_appengine/dev_appserver.py
